# This cert.conf is for the service running on localhost:4001
[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
# Note: We're removing req_extensions here, and moving to -extensions in the command

[dn]
CN = spotify.local

[v3_req] # Changed name from [req_ext]
subjectAltName = @alt_names
basicConstraints = CA:TRUE  # Essential for self-signed certs acting as a CA or root
keyUsage = digitalSignature, keyEncipherment, cRLSign, keyCertSign # Common usage for self-signed

[alt_names]
DNS.1   = localhost
IP.1    = 127.0.0.1
DNS.2   = beatmatch.cs.colman.ac.il
IP.2    = 193.106.55.87