[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
req_extensions     = req_ext
distinguished_name = dn

[dn]
CN = localhost.local # Or keep spotify.local, but better to match the hostname

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1   = beatmatch.cs.colman.ac.il
IP.1    = 193.106.55.87
DNS.2   = localhost
IP.2    = 127.0.0.1