[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
req_extensions     = req_ext
distinguished_name = dn

[dn]
CN = spotify.local # Or localhost.local, less critical than SANs for client trust

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1   = localhost      # Essential for connecting to 'localhost'
IP.1    = 127.0.0.1      # Essential for connecting to '127.0.0.1'
# Keep other entries if needed for other access points:
DNS.2   = beatmatch.cs.colman.ac.il
IP.2    = 193.106.55.87